In [26]:
#Libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [27]:
#Importing Dataset
dataset = pd.read_csv('/home/quartesa/Desktop/Machine Learning/1.Regressions/House_Price_Guesser/dataset.csv')
x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [28]:
#Encoding Data(House Location)
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
x[:,2] = encoder.fit_transform(x[:,2])

In [29]:
#Model Selection(Linear Regression)
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x,y)

LinearRegression()

In [30]:
#Linear Regression R2 Score
from sklearn.metrics import r2_score
y_pred = lin_reg.predict(x)
print('Linear Regression R2: {}'.format(r2_score(y,y_pred)))

Linear Regression R2: 0.9757061629949462


### Linear Regression's R2 Score is quite well so i am not going to try finding another model

In [32]:
#Checking X
print(x)
"""
Central Coded with 0
Suburban Coded with 1
"""

[[3 150 0 2005]
 [4 200 1 2010]
 [2 100 0 1998]
 [5 250 1 2015]
 [4 180 0 2012]
 [3 130 0 2008]
 [4 220 1 2017]
 [2 95 1 2000]
 [3 140 0 2006]
 [5 270 1 2020]
 [3 160 0 2009]
 [4 190 1 2013]
 [2 110 1 2002]
 [3 135 0 2007]
 [4 210 0 2014]
 [2 105 0 2001]
 [5 260 1 2019]
 [3 155 1 2011]
 [4 195 0 2016]
 [2 120 0 2003]
 [3 165 0 2010]
 [4 205 1 2015]
 [2 95 0 1999]
 [5 245 1 2018]
 [4 175 0 2013]
 [3 125 0 2007]
 [4 215 1 2016]
 [2 100 1 2001]
 [3 145 0 2005]
 [5 275 1 2021]
 [3 155 0 2011]
 [4 185 1 2014]
 [2 115 1 2003]
 [3 140 0 2008]
 [4 220 0 2015]
 [2 110 0 2002]
 [5 255 1 2020]
 [3 160 1 2012]
 [4 200 0 2017]
 [2 125 0 2004]
 [3 170 0 2009]
 [4 210 1 2016]
 [2 95 1 2000]
 [3 145 0 2006]
 [4 225 1 2017]
 [2 105 0 2001]
 [5 265 0 2018]
 [3 150 1 2013]
 [4 195 1 2019]
 [2 115 0 2004]
 [3 165 0 2011]
 [4 215 1 2016]
 [2 100 0 1999]
 [3 150 1 2005]
 [4 230 0 2014]
 [2 110 1 2003]
 [5 260 0 2019]
 [3 155 0 2010]
 [4 195 1 2015]
 [2 120 0 2006]
 [3 170 1 2012]
 [4 200 0 2017]
 [2 125 1 2

'\nCentral Coded with 0\nSuburban Coded with 1\n'

In [33]:
#Predicting A Price
print('House Price: {}'.format(lin_reg.predict([[4,190,0,2009]])))

House Price: [305113.98267369]


### It is a good Guess Our Guesser Finish in Here